---
# tasks file for vector-role
- name: Install, configure, and start Vector
  block:
    - name: Get vector distrib
      ansible.builtin.get_url:
        url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
        dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
        mode: "0644"
    - name: Install vector
      become: true
      become_method: su
      ansible.builtin.yum:
        disable_gpg_check: True
        name: vector-{{ vector_version }}-1.x86_64.rpm
      notify: Restart vector service
    - name: Configure Vector | ensure what directory exists
      ansible.builtin.file:
        path: "{{ vector_config_dir }}"
        state: directory
        mode: "0644"
    - name: Configure Vector | Template config
      ansible.builtin.template:
        src: vector.yml.j2
        mode: "0644"
        dest: "{{ vector_config_dir }}/vector.yml"
    - name: Configure Service Vector| Template systemd unit
      become: true
      become_method: su
      ansible.builtin.template:
        src: vector.service.j2
        dest: /etc/systemd/system/vector.service
        mode: "0644"
      notify: Restart vector service
  when: ansible_os_family == "RedHat"
