---
driver:
  name: docker
platforms:
  - name: instance
    image: quay.io/centos/centos:stream8
    pre_build_image: true
  - name: oraclelinux_8
    image: docker.io/oraclelinux:8
    pre_build_image: true
  - name: centos7
    image: docker.io/centos:centos7
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
